services:
  # order-service:
  #   image: node:20-alpine
  #   working_dir: /app
  #   command: sh -c "npm ci && npm run start:dev"
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     PORT: 3000
  #     NODE_ENV: development
  #     PG_HOST: order_postgres
  #     PG_PORT: 5432
  #     PG_USER: order_user
  #     PG_PASSWORD: order_pass
  #     PG_DB: order_read_db
  #     ESDB_HOST: eventstore
  #     ESDB_PORT: 2113
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     REDIS_PASSWORD: ''
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   depends_on:
  #     order_postgres:
  #       condition: service_healthy
  #     eventstore:
  #       condition: service_started
  #     redis:
  #       condition: service_started

  order_postgres:
    image: postgres:13-buster
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: order_read_db
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U order_user -d order_read_db']
      interval: 5s
      timeout: 3s
      retries: 20

  eventstore:
    image: eventstore/eventstore:23.10.0-bookworm-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

volumes:
  pg_data:
  eventstore-volume-data:
  eventstore-volume-logs:
